FROM golang:1.16-alpine as build

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go .

RUN go build -o /restapi

EXPOSE 10000

CMD [ "/restapi" ]

FROM alpine:latest

WORKDIR /

COPY --from=build /restapi /restapi

EXPOSE 10000


ENTRYPOINT ["/restapi"]